FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy project files (będzie robił bind-mount i tak)
# COPY . .

# Permissions (opcjonalnie)
# RUN chown -R www-data:www-data /var/www/html

# Expose port (jeśli potrzebne — tu raczej nginx przed fpm powinien być)
# EXPOSE 9000

CMD ["php-fpm"]
